# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Asmodehn's Lair
email: asmodehn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Asmodehn's Dev Workshop. We specialize in developing 
  software components and tools for games, simulations and various cloud applications. 
  We help bring to life, run and maintain all kinds of distributed systems.
  We are focusing on developing solutions for self sustaining complex systems.
  If you are looking for help on your software journey, do not hesitate to get in touch.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: asmodehn
github_username:  asmodehn

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal #minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
